# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField(blank=True)),
                ('description', models.TextField()),
                ('key_accomplishments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=80), size=None)),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=b'pdf_attachments/'), size=None)),
            ],
        ),
    ]
