# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(default=b'ROCK STAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='employer',
            field=models.CharField(max_length=50),
        ),
    ]
