# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170625_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('exp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Experience')),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=80)),
                ('major', models.CharField(max_length=50)),
                ('minor', models.CharField(max_length=50)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            bases=('blog.experience',),
        ),
        migrations.CreateModel(
            name='VolunteerExperience',
            fields=[
                ('exp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Experience')),
                ('org', models.CharField(max_length=80)),
                ('summary', models.CharField(max_length=80)),
                ('reason', models.TextField()),
            ],
            bases=('blog.experience',),
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='Exp',
            new_name='exp',
        ),
    ]
