# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:14
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170625_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=b'pdf_attachments/'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='key_accomplishments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=80), blank=True, null=True, size=None),
        ),
    ]
