# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170625_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationexperience',
            name='exp',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Experience'),
        ),
        migrations.AlterField(
            model_name='volunteerexperience',
            name='exp',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Experience'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='exp',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Experience'),
        ),
    ]
