# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='key_accomplishments',
        ),
    ]
