# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 23:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_experience_key_accomplishments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='attachments',
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default=b'LOC_CITY, LS', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(default=b'description here'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(default=b'article entry here'),
        ),
        migrations.AlterField(
            model_name='shortbio',
            name='bio',
            field=ckeditor.fields.RichTextField(default=b'bio here'),
        ),
    ]
