# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170718_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkExperience',
            new_name='ProfessionalExperience',
        ),
    ]
