# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 05:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170719_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='obj',
            field=ckeditor.fields.RichTextField(default=b'objective here'),
        ),
    ]
